-- BizMaster SaaS — Membership Phase 1 MVP
-- Supabase SQL Editor에서 이 파일 내용을 붙여넣고 실행하세요.
-- (Database > SQL Editor > New query > 내용 붙여넣기 > Run)

-- ─── memberships 테이블 ───────────────────────────────────────────
create table if not exists memberships (
  id                          bigint generated by default as identity primary key,
  email                       text unique not null,
  name                        text,
  plan                        text not null check (plan in ('standard','premium')),
  starts_at                   date not null default current_date,
  expires_at                  date not null,
  monthly_quota_ai_report     integer not null default 0,
  monthly_quota_premium_report integer not null default 0,
  used_ai_this_month          integer not null default 0,
  used_premium_this_month     integer not null default 0,
  quota_reset_at              date not null default current_date,
  is_active                   boolean not null default true,
  note                        text,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);

create index if not exists idx_memberships_email  on memberships(email);
create index if not exists idx_memberships_active on memberships(is_active, expires_at);

-- ─── membership_usage 테이블 ─────────────────────────────────────
create table if not exists membership_usage (
  id            bigint generated by default as identity primary key,
  membership_id bigint references memberships(id) on delete cascade,
  email         text not null,
  service_type  text not null check (service_type in ('simple_analysis','ai_report','premium_report')),
  used_at       timestamptz not null default now(),
  metadata      jsonb
);

create index if not exists idx_membership_usage_email on membership_usage(email, used_at);

-- ─── updated_at 자동 갱신 함수 + 트리거 ────────────────────────────
create or replace function update_updated_at_column()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_memberships_updated_at on memberships;
create trigger trg_memberships_updated_at
  before update on memberships
  for each row execute function update_updated_at_column();
